# -*- coding: utf-8 -*-
"""Ejercicio2_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ylvb1lCNpdJbmm5Ij2gmidjthxnkrj_k

Ejercicio_2.2
"""

from enum import Enum

class TipoPlaneta(Enum):
    GASEOSO = "Gaseoso"
    TERRESTRE = "Terrestre"
    ENANO = "Enano"

class Planeta:
    def __init__(self, nombre: str, cantidad_satelites: int, masa: float,
                 volumen: float, diametro: int, distancia_sol: int,
                 tipo: TipoPlaneta, es_observable: bool):
        self.nombre = nombre
        self.cantidad_satelites = cantidad_satelites
        self.masa = masa
        self.volumen = volumen
        self.diametro = diametro
        self.distancia_sol = distancia_sol
        self.tipo = tipo
        self.es_observable = es_observable

    def imprimir(self):
        masa_str = f"{self.masa:E}".replace("E+0", "E")
        volumen_str = f"{self.volumen:E}".replace("E+0", "E")
        densidad_str = f"{self.calcular_densidad():E}".replace("E+0", "E")

        print(f"Nombre del planeta = {self.nombre}")
        print(f"Cantidad de satélites = {self.cantidad_satelites}")
        print(f"Masa del planeta = {masa_str}")
        print(f"Volumen del planeta = {volumen_str}")
        print(f"Diámetro del planeta = {self.diametro}")
        print(f"Distancia al sol = {self.distancia_sol}")
        print(f"Tipo de planeta = {self.tipo.name}")
        print(f"Es observable = {str(self.es_observable).lower()}")
        print(f"Densidad del planeta = {densidad_str}")
        print(f"Es planeta exterior = {str(self.es_planeta_exterior()).lower()}")

    def calcular_densidad(self) -> float:
        if self.volumen == 0:
            return 0
        return self.masa / self.volumen

    def es_planeta_exterior(self) -> bool:
        limite = 149597870 * 3.4
        return self.distancia_sol > limite
class EjercicioN22:
  if __name__ == "__main__":

      tierra = Planeta(
          nombre="Tierra",
          cantidad_satelites=1,
          masa=5.9736e24,
          volumen=1.08321e12,
          diametro=12742,
          distancia_sol=150000000,
          tipo=TipoPlaneta.TERRESTRE,
          es_observable=True
      )

      jupiter = Planeta(
          nombre="Júpiter",
          cantidad_satelites=79,
          masa=1.899e27,
          volumen=1.4313e15,
          diametro=139820,
          distancia_sol=750000000,
          tipo=TipoPlaneta.GASEOSO,
          es_observable=True
      )

      tierra.imprimir()
      print()
      jupiter.imprimir()